import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import Head from "next/head";

import { moviesApi } from "@/api/movies";

import { usePopularMovies } from "@/hooks/queries/usePopularMovies";
import { useMovieDetail } from "@/hooks/queries/useMovieDetail";

import { MovieDetailModal } from "@/components/MovieDetailModal";

import { MovieItem } from "@/types/Movie.types";
import { MovieDetailResponse } from "@/types/MovieDetail.types";

import HomeView from "@/components/HomeView";
import { useRouter } from "next/router";

export const getServerSideProps = (async ({ params }) => {
  const moviesData = await moviesApi.getPopular();
  const movies: MovieItem[] = moviesData.data.results;

  if (!params) return { props: { movies } };

  const movieId = params.id;

  const movieDetail = await moviesApi.getDetail(Number(movieId));

  return {
    props: {
      movies,
      movie: movieDetail.data,
    },
  };
}) satisfies GetServerSideProps<{
  movies: MovieItem[];
  movie?: MovieDetailResponse;
}>;

export default function MovieDetail({
  movies: initialMovies,
  movie: initialMovie,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const router = useRouter();

  const { data: movies } = usePopularMovies({ initialMovies });
  const { data: movie } = useMovieDetail({ initialMovie });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {movies && <HomeView movies={movies} />}
      {movie && (
        <MovieDetailModal
          movie={movie}
          onClose={() => {
            router.push("/");
          }}
        />
      )}
    </>
  );
}
