import { moviesApi } from '@/api/movies';

import { GetServerSidePropsContext, InferGetServerSidePropsType } from 'next';
import { useRouter } from 'next/router';
import { MovieDetailModal } from '@/components/MovieDetailModal';

import Home from '@/pages/index';
import Head from 'next/head';

// 상세 페이지의 getServerSideProps
export async function getServerSideProps({
  params,
}: GetServerSidePropsContext<{ movieId: string }>) {
  const movieId = params?.movieId;

  if (!movieId || !/^\d+$/.test(movieId)) {
    return { notFound: true };
  }

  const { data: movieData } = await moviesApi.getPopular();
  const { data: movieDetailData } = await moviesApi.getDetail(Number(movieId));

  return { props: { movies: movieData.results, movieDetail: movieDetailData } };
}

export default function MovieDetailPage({
  movies,
  movieDetail,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const router = useRouter();

  // 메타데이터 구성
  const title = movieDetail.title;
  const description = movieDetail.overview;
  const imageUrl = `https://image.tmdb.org/t/p/original${movieDetail.poster_path}`;

  return (
    <>
      <Head>
        <meta property="og:title" content={title} key="og:title" />
        <meta
          property="og:description"
          content={description}
          key="og:description"
        />
        <meta property="og:image" content={imageUrl} key="og:image" />
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home movies={movies} />
      <MovieDetailModal
        movie={movieDetail}
        onClose={() => void router.push('/')}
      />
    </>
  );
}
